import { test, expect } from '@playwright/test'
test('multi-char compile', async ({ page }) => {
  test.setTimeout(540000)
  page.on('pageerror', (e) => console.log('PAGEERROR:', (e.stack || e.message).slice(0, 200)))
  await page.goto('http://inktrail.localhost:5173/')
  await page.getByRole('button', { name: /这一次/ }).waitFor({ state: 'visible', timeout: 240000 })
  await page.getByRole('button', { name: /这一次/ }).click()
  await page.getByPlaceholder('一个字或一句话').fill('一二')
  await page.getByRole('button', { name: '编译成路线' }).click()
  await expect(page.locator('.stats dd').first()).toBeVisible({ timeout: 300000 })
  console.log('STATS:', (await page.locator('.stats').textContent())?.replace(/\s+/g, ' '))
  await page.waitForTimeout(3000)
  await page.screenshot({ path: 'e2e/artifacts/multichar.png' })
  console.log('DONE')
})
